- name: Manage EVE-NG Devices
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Enable OSPF globally
      ios_config:
        authorize: yes
        parents: router ospf 1
        lines: 
          - network 0.0.0.0 0.0.0.0 area 0

      register: print_output

    - debug: var=print_output.stdout_lines
