---
- name: Manage EVE-NG Devices
  hosts: Router55, Router54, Switch64
  gather_facts: false
  connection: local

  vars:
    cli:
      username: admin
      password: cisco
  #    transport: cli  # → Got an error with this. 

  tasks:
    - name: Enable OSPF globally
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines: 
          - network 0.0.0.0 0.0.0.0 area 0

      register: print_output

    - debug: var=print_output.stdout_lines

