---
- name: GET ARP information
  hosts: all
  gather_facts: false

  tasks:
    - name: show arp
      raw: "show running-config"

      register: print_output

    - debug: var=print_output.stdout_lines

