---
- name: Ports Security Configs
  hosts: eve_ng_dc_switches
  gather_facts: false
  connection: local

  vars:
    cli:
      username: admin
      password: cisco

  tasks:
    - name: Interface settings
      ios_config:
        provider: "{{ cli }}"
        parents: "interface {{ item.interface }}"
        lines:
          - "switchport access vlan {{ item.vlan }}"
          - "switchport voice vlan {{ item.voice_vlan }}"
          - switchport host
          - switchport port-security maximum 2 
          - switchport port-security
          - switchport port-security aging time 2
          - switchport port-security aging type inactivity 
          - switchport port-security violation restrict 
          - ip arp inspection limit rate 100
          - ip dhcp snooping limit rate 100
          - ip verify source
          - ipv6 nd raguard attach-policy HOST_POLICY
        after:
          - no shutdown
      with_items:
        - { interface : GigabitEthernet1/0, vlan : 100, voice_vlan : 101 }
        - { interface : GigabitEthernet1/1, vlan : 10, voice_vlan : 101 }
        - { interface : GigabitEthernet1/2, vlan : 20, voice_vlan : 101 }
        - { interface : GigabitEthernet1/3, vlan : 30, voice_vlan : 101 }

      register: print_output

    - debug: var=print_output


